"""
Generate the report's hyperparameter table from the saved models.

The table in report.tex used to be maintained by hand and drifted away from the
persisted estimators twice: the pickles are the authoritative record of what
GridSearchCV actually selected, so the table has to be derived from them rather
than transcribed. Run this after any run that retrains, and re-upload the
generated file alongside report.tex.

    python tools/dump_hyperparams.py

Writes tables/hyperparams.tex, which report.tex pulls in with
\\input{tables/hyperparams}.

The SEARCH_GRIDS dictionary below mirrors the grids in src/models/models.py.
It has to be kept in step with that file by hand -- the grids are not recorded
in the fitted estimator, so there is nothing to read them back from. Everything
else on the table, including which values sit at an extreme of their grid, is
computed from the pickles.
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from src.models import load_model, model_exists  # noqa: E402

OUTPUT_PATH = os.path.join("tables", "hyperparams.tex")

# (model key on disk, display name, [(param, LaTeX label, grid), ...])
# Grids mirror src/models/models.py. 'None' is written as a Python None.
SEARCH_GRIDS = [
    ("knn", "$K$-NN", [
        ("n_neighbors", r"\texttt{n\_neighbors}", [3, 5, 7, 9, 11, 31, 51, 101, 151, 200]),
    ]),
    ("linear_svm", "Linear SVM", [
        ("C", r"\texttt{C}", [0.1, 1.0, 10.0]),
    ]),
    ("rbf_svm", "RBF SVM", [
        ("C", r"\texttt{C}", [0.1, 1.0, 10.0]),
        ("gamma", r"\texttt{gamma}", ["scale", "auto"]),
    ]),
    ("random_forest", "Random Forest", [
        ("n_estimators", r"\texttt{n\_estimators}", [100, 200, 300]),
        ("max_depth", r"\texttt{max\_depth}", [10, 20, 30, None]),
        ("min_samples_split", r"\texttt{min\_samples\_split}", [2, 5, 10]),
        ("min_samples_leaf", r"\texttt{min\_samples\_leaf}", [1, 2, 4]),
    ]),
    ("xgboost", "XGBoost", [
        ("n_estimators", r"\texttt{n\_estimators}", [100, 150, 200]),
        ("max_depth", r"\texttt{max\_depth}", [4, 6]),
        ("learning_rate", r"\texttt{learning\_rate}", [0.05, 0.1]),
        ("subsample", r"\texttt{subsample}", [0.8, 1.0]),
    ]),
]


def fmt_value(value):
    """Render a selected hyperparameter value the way the report writes numbers."""
    if value is None:
        return "None"
    if isinstance(value, bool):
        return str(value)
    if isinstance(value, float):
        return f"{value:g}" if value != int(value) else f"{value:.1f}"
    return str(value)


def fmt_grid(grid):
    """
    Render a search grid, collapsing the long K-NN list to a range.

    Numeric levels go inside one math group so they align with the notation used
    elsewhere in the report; string levels and None stay in text mode, since
    "None" typeset as math reads as a product of four italic variables.
    """
    if len(grid) > 6:
        return f"{len(grid)} values in $[{fmt_value(grid[0])}, {fmt_value(grid[-1])}]$"
    if all(isinstance(v, str) for v in grid):
        return ", ".join(grid)
    numeric = [v for v in grid if v is not None and not isinstance(v, str)]
    body = r",\ ".join(fmt_value(v) for v in numeric)
    rendered = f"${body}$"
    if any(v is None for v in grid):
        rendered += ", None"
    return rendered


def is_at_extreme(value, grid):
    """
    True when the selected value sits at either end of a grid of three or more
    levels. Two-level grids are excluded: with only two options every choice is
    trivially an extreme, so marking them would say nothing.
    """
    if len(grid) < 3:
        return False
    return value == grid[0] or value == grid[-1]


def cell(model_key, param, grid, use_big_data):
    """The table cell for one hyperparameter in one arena."""
    if not model_exists(model_key, use_big_data=use_big_data):
        return "---"
    model = load_model(model_key, use_big_data=use_big_data)
    params = model.get_params()
    if param not in params:
        return "---"
    value = params[param]
    text = fmt_value(value)
    return rf"\textbf{{{text}}}" if is_at_extreme(value, grid) else text


def build_table():
    lines = [
        "% Generated by tools/dump_hyperparams.py -- do not edit by hand.",
        "% Values are read back from the persisted estimators in saved_models*/,",
        "% which are the authoritative record of what GridSearchCV selected.",
        r"\begin{table}[H]",
        r"\centering",
        r"\caption{Search space and selected hyperparameters per arena. Bold marks a"
        r" value selected at an extreme of a grid of three or more levels. A dash marks"
        r" a model not trained in that arena. The two baselines of"
        r" Section~\ref{sec:results} carry no tuned hyperparameters and are omitted:"
        r" they are left un-tuned by design, so that they measure a floor rather than"
        r" compete.}",
        r"\label{tab:hyperparams}",
        r"\small",
        r"\begin{tabular}{llccc}",
        r"\toprule",
        r"\textbf{Model} & \textbf{Hyperparameter} & \textbf{Search grid} &"
        r" \textbf{Balanced} & \textbf{Full data} \\",
        r"\midrule",
    ]

    blocks = []
    for model_key, display, params in SEARCH_GRIDS:
        rows = []
        for i, (param, label, grid) in enumerate(params):
            name = display if i == 0 else ""
            rows.append(
                f"{name} & {label} & {fmt_grid(grid)} & "
                f"{cell(model_key, param, grid, False)} & "
                f"{cell(model_key, param, grid, True)} " + r"\\"
            )
        blocks.append("\n".join(rows))

    lines.append(("\n" + r"\midrule" + "\n").join(blocks))
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    return "\n".join(lines)


def main():
    table = build_table()
    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
    with open(OUTPUT_PATH, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(table)
    print(table)
    print(f"\nWritten to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
